[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "wbauEhzu1CGBTsbzW2VpFfKrsStuNDi7YMw3Uj5WBvf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
