[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "E5K3rtGD7nEvSqHTxeNfEChvcrd3xiKUkKNY9zQWam1K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
